language: python
python:
  - "3.5"
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install tox
  - pip install coveralls
script: tox
after_success: coveralls
